language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
node_js:
  - "0.12"
  - "4.2"
